services:
  db:
    image: postgres:15
    container_name: wallhub_db
    restart: always
    environment:
      POSTGRES_USER: user_wallpapers
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: wallhub_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: